package betterprogrammer;

import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

//STRING  hashset, throwable, 
//public class BetterProgrammerTask {
//
//    public static boolean isPalindrome(String s) {
//            
//            /*          Definition: A palindrome is a string that reads the same forward and backward.
//                      For example, "abcba" is a palindrome, "abab" is not.
//                                Please implement this method to
//                                          return true if the parameter is a palindrome and false otherwise.
//                                            */       
//                                                	if (s==null ){
//                                                	    		return false;
//                                                	    		    	}
//                                                	    		    	    	int len=s.length();
//                                                	    		    	    	    	
//                                                	    		    	    	    	    	if(len==1|| len==0)
//                                                	    		    	    	    	    	    	{
//                                                	    		    	    	    	    	    	    		return true;
//                                                	    		    	    	    	    	    	    		    	}
//                                                	    		    	    	    	    	    	    		    	    	//boolean isEvenlen=s.length()%2==0?true:false;
//                                                	    		    	    	    	    	    	    		    	    	    	int intchecklen=s.length()/2;//isEvenlen?s.length()/2:s.length()/2+1;
//
//                                                	    		    	    	    	    	    	    		    	    	    	    	for(int i=0;i<intchecklen;i++)//only check half of the length
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	{
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		if (s.charAt(i)!=s.charAt(len-i-1)) return false;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	}
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	return true;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		    }
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		        
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		          public static Set<Object> getUniqueElements(Set<Object> a, Set<Object> b) {
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                  /*
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                            Please implement this method to
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                      return a set of elements that can be found only in set a or set b,
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                but not in both Sets.
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                          The method should not change the content of the parameters.
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   */
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	  
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	Set finaldiff=new HashSet<Object>();
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	if (a==null && b==null)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		return finaldiff;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	if (a==null)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			return b;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	if (b==null)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			return a;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	Set diff=new HashSet<Object>();
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	diff.addAll(a);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	diff.removeAll(b);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	finaldiff.addAll(diff);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	diff.clear();
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	diff.addAll(b);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	diff.removeAll(a);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	finaldiff.addAll(diff);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	//    	if(ahasNull && bhasNull)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	//    		finaldiff.remove(null); //We do that to remove nulls (if we want) because null!=null
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	return finaldiff;    	
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	    }
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	public static double getProbability(int Y, int X) {
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	        /*
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                  If you roll Y standard six-sided dice, what.s the probability that 
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                            you get at least X 4s?
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                      To calculate that you should divide the number of comibnations 
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                with X or more 4s
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                          by the total number of possible combinations.
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                   */
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	double sumprob=0;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	if(Y<=0 || X<0 || Y<X)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		return 0;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	//if(Y==X)return 1/6;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	//((y*y-1*y-2*y-3..y-(x+1))/(y-x)!) *(1/6)^x*(5/6)^(y-x);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	for(int x=X;x<=Y;x++)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	{
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		double numtrprod=1;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	int ysubx=Y-x;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		double ysubxfact=factorial(ysubx);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		for(int i=Y;i<Y-x;i--)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			numtrprod*=i;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		sumprob+=(Math.pow(5, (Y-x))*numtrprod)/(ysubxfact*Math.pow(6, Y));
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	}
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    		
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			return sumprob;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			    }
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			        public static long factorial(int num)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			            {
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	if(num<=1)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		return 1;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	else
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		return num*factorial(num-1);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		    }
//
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        static List<String> Hanoians=new LinkedList<String>();		
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	public static List<String> transferFromAtoC(int n) {
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	        /*
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                  Towers Of Hanoi.
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                            There are three pegs: A, B and C. There are n disks. All disks are different in size.
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                      The disks are initially stacked on peg A so that they increase in size from the top to the bottom.
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                The goal is to transfer the entire tower from the A peg to the C peg.
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                          One disk at a time can be moved from the top of a stack either to an empty peg or to
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                    a peg with a larger disk than itself on the top of its stack.
//
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                              The method should return a sequence of disk moves, each move is a String with two letters (A, B or C)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                        corresponding to the peg the disk moves from and the peg it moves to.
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                  For example, the move "AC" means that a top disk from peg A should be moved to peg C.
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                           */
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	Hanoians.clear();
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	moveFromViaTo('A','B','C',n);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	return Hanoians;		//move('B','C','A',n);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		    }
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		        public static void moveFromViaTo(char peg1, char peg2,char peg3, int n)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		            {
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	if (n==0) return ;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    	if(n==1){Hanoians.add(peg1+""+peg3);}
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			if(n>1) {
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		moveFromViaTo(peg1,peg3,peg2,n-1);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		Hanoians.add(peg1+""+peg3);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		moveFromViaTo(peg2,peg1,peg3,n-1);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	}
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	    }
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	        
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	            public static void main(String[] args)
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                {
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	System.out.println(BetterProgrammerTask.isPalindrome(""));
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	//    	if(true) return;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	System.out.println(BetterProgrammerTask.getProbability(1, 0));
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	  //  	if (true) return;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	Set diff=new HashSet<String>();
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	diff.add("a");
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	diff.add("b");
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	diff.add("c");
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	diff.add(null);
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	Set hey=null;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	Set diff1=new HashSet<String>();
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	    	diff1.add("a");
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	    	    	diff1.add("b");
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	    	    	    	diff1.add("cc");
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	    	    	    	    	diff1.add("c");
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	    	    	    	    	    	System.out.println(BetterProgrammerTask.getUniqueElements(diff1, hey));
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	    	    	    	    	    	    	//if (true)return;
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	    	    	    	    	    	    	    	System.out.println(BetterProgrammerTask.transferFromAtoC(3));
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	    	    	    	    	    	    	    	    	if(true) return;
//
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	    	    	    	    	    	    	    	    	    }
//                                                	    		    	    	    	    	    	    		    	    	    	    	    	    		    	    	    		                                                                   	  	      	    	    		    	    			    	    			    	    	    	    	    	    	    	    	    	    	    	        	                                                                       	    	    		    	    	    	    	    		        	    		    		    			    		    		    	    			                	    		    	    		        	                                                                                                               	    	    	    		                	    			    		    		    		    	                    	    	    	      	    	    	    	    	    	    	    	    	    	    	    	    	    	    	    }
